### PR TITLE
Adds documentation resolve to method completion

### PR DESCRIPTION
**Pull request by laginha87**
Adds the method signature to the completion box and the documentation of the method if it has any. 

ezgif com-video-to-gif 1
ezgif com-video-to-gif

### CODE REVIEW

**Comment by faustinoaq** [comment]
@laginha87 I messed up the commit history trying to release v0.7.0 I apologize for this :sweat: 

I already published v0.7.0 successfully but this PR have some commits that don't exist on master, so, can you please `--force` a sync with master repo? :sweat_smile:

**Comment by laginha87** [comment]
no worries I'll do that when I can 👍

**Comment by keplersj** [comment]
Here's corresponding LSP Documentation: [Signature Help Request](https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp)

**Comment by bew** [comment]
Nice one, but I meant in the completion menu

**Comment by faustinoaq** [comment]
@keplersj your screen captures look awesome! :+1: I'll give a try to atom again :smile:

**Pull request merged**
