### PR TITLE
Move params to RequestMessage

### PR DESCRIPTION
**Pull request by bmulvihill**
It seems a couple of the Params are in the wrong MessageType.

Based on the LSP 3.0 Spec the [`TextDocumentPositionParams`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textdocumentpositionparams)  and [`DocumentFormattingParams`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-formatting-request) are associated with Request Messages

### CODE REVIEW

**Comment by faustinoaq** [comment]
Thanks you! :+1: 

I will take some days to review this :sweat_smile:

**Comment by faustinoaq** [comment]
@keplersj seems that Travis is failing again

**Comment by faustinoaq** [comment]
All seems to be working well :smile:  Thanks you for you contribution!

ezgif-3-4f343952a8

WDYT @keplersj ?

**Comment by keplersj** [comment]
Looks cool.

**Pull request merged**
