### PR TITLE
Update crystal to v0.25.0

### PR DESCRIPTION
**Pull request by faustinoaq**
This PR still needs to fix some breaking changes :sweat_smile:

### CODE REVIEW

**Comment by faustinoaq** [comment]
```
no overload matches 'JSON::MappingError.new' with types (String | Nil), String, Regex, Int32, Int32, JSON::ParseException+
Overloads are:
 - JSON::MappingError.new(message : String | ::Nil, klass : String, attribute : String | ::Nil, line_number : Int32, column_number : Int32, cause)
```

^^ Crystal v0.25.0 incompatibility issue here :sweat_smile: 

Ref: https://travis-ci.org/crystal-lang-tools/scry/jobs/392784317#L1123

**Comment by faustinoaq** [comment]
Oh, at least specs are compiling now :tada: 

@laginha87 looks like completion specs are the only one failing on v0.25.0, any clue? :sweat_smile:

**Comment by laginha87** [comment]
@faustinoaq the tests check autocomplete results for crystal language apis, it seems like new methods and classes were added in 0.25. Just adding what's missing to the expected should be enough.
Not sure how we can shield ourselves from further upgrades in the futures as we want to check that those get completed.

**Comment by faustinoaq** [comment]
> do you want me to fix the specs ?

Please :sweat_smile:

**Comment by faustinoaq** [comment]
@laginha87 Thank you! :+1:

**Comment by bew** [comment]
Anything else to do here?

**Comment by faustinoaq** [comment]
@bew No, I think this is ready, let's merge! :+1:

**Comment by faustinoaq** [comment]
@bew Can you approve/review? :sweat_smile:

**Comment by bew** [comment]
There are a few `# Will be replaced by .scry.yml` with comments below, is it related to the 0.25 upgrade?
If not, I think it should go in another PR.

**Comment by faustinoaq** [comment]
@bew Yeah, this is a workaround, and is also related to v0.25.0 breaking changes, see: https://travis-ci.org/crystal-lang-tools/scry/jobs/393192687#L2786

Maybe we should fix it as well?

```
no overload matches 'Scry::Settings#to_json' with type JSON::Builder
Overloads are:
 - Object#to_json(io : IO)
 - Object#to_json()
```

No idea, what this mean, though :sweat_smile:

**Comment by bew** [comment]
I made a branch for the update: https://github.com/bew/scry/tree/2277b79fbb3f3b73081c8121e9cb173f891ade80
without the workaround for Settings (I removed commits 8742e0a and 11992e8)

Now I get an error for the `JSON.mapping` expansion of `Scry::Settings`:
```
no overload matches 'JSON::MappingError.new' with types (String | Nil), String, Regex, Int32, Int32, JSON::ParseException+
Overloads are:
 - JSON::MappingError.new(message : String | ::Nil, klass : String, attribute : String | ::Nil, line_number : Int32, column_number : Int32, cause)
```
It's not clear at first, but it complains about the key. Here is the mapping for Settings:
```cr
  struct Settings
    JSON.mapping({
      crystal_config: {type: Customizations, key: /^crystal.*/, default: Customizations.from_json("{}")},
    })
  end
```
The issue is the Regex for the key. If you need something specific to match the key it might be easier to implement the 'mapping' yourself (and this one looks quite easy).

**Comment by bew** [comment]
And I just did a "fix": https://github.com/bew/scry/commit/38fe04d13b024a2c5a083843652844d2141ab2bf

Let me know what you think

**Comment by bararchy** [comment]
@bew looks good from my side, @faustinoaq pull, update & merge?

**Comment by faustinoaq** [comment]
@bararchy Hi, sorry for my big delay on this, I has been very busy on latest month :sweat_smile: 

I will try to look into this in some days. Cheers :+1:

**Comment by bmulvihill** [comment]
Closing since #131 was merged

**Pull request closed without merging**
